### ISSUE TITLE
Using `verify!` on a type that does not implement Copy

### ISSUE THREAD

**Issue by ProgVal** [Geal/nom#794] opened 2018-06-16 11:33 UTC
The borrow checker does not allow this, because the `name` is moved to the lambda:

```rust
const KEYWORDS: [&'static str; 1] = ["yield"];
named!(pub name<StrSpan, String>,                                                          
  verify!(                                                                                 
    // a subparser that returns a String                                                                               
    |name: String| !KEYWORDS.contains(&&name[..])
  )                                                                                        
);                                                                                         
```

A solution would be change `verify!` to expect a lambda whose argument is a reference to the value, but that would be a breaking change.

Workaround:

```rust
const KEYWORDS: [&'static str; 1] = ["yield"];
named!(pub name<StrSpan, String>,                                                          
  do_parse!(                                                                               
    name: /* the subparser */ >>                                                                                   
    verify!(tag!(""), |_| !KEYWORDS.contains(&&name[..])) >>
    (name)                                                                                 
  )                                                                                        
);                                                                                         
```

**Comment by xpayn** [comment] 2018-06-19 08:27
This seems to be a duplicate of #510 
But anyway, I made my own input type that is non-copy and i have problems with other combinators...
Maybe an issue about making combinators working with non-copy input would be more generic and a good fit for nom 4.1

**Comment by ProgVal** [comment] 2018-06-19 08:37
Indeed, thanks for the ref. (If no one minds, I'll keep this issue open as a reminder to myself in case I have time to fix it)

**Comment by juchiast** [comment] 2018-07-10 14:46
I have a different workaround for this. Instead of `verify!`, I use `map!` with a function that return Ok(data) on valid data, and Err(_) otherwise,

**Comment by Geal** [comment] 2019-05-06 14:25
it is done in 717e7f0595de for the upcoming nom 5, `verify` will now take a reference in all cases

**Closed by Geal** 2019-05-06 14:25 UTC
