### ISSUE TITLE
delimited! (specifically tuple_parser!) is incompatible with method calls (call_m!)

### ISSUE THREAD

**Issue by lucasem** [Geal/nom#728] opened 2018-04-02 16:22 UTC
On rust 1.25.0 with nom 4.0.0-beta2.

Using `delimited!` expands into `tuple_parser!` which moves method-related functionality into a closure. Here's a practical example where we want to keep track of all `u32`s that have been parsed, where `read_list` parses a list (e.g. `[2,4,0]`) using `delimited!`:

```rust
#[macro_use]
extern crate nom;
use std::collections::HashSet;
use std::num::ParseIntError;
use nom::{digit, IResult};
use nom::types::CompleteStr;

fn nom_u32(inp: CompleteStr) -> Result<u32, ParseIntError> {
    inp.0.parse()
}

pub struct Registry {
    numbers: HashSet<u32>,
}
impl Registry {
    fn reg_num(mut self, inp: CompleteStr, n: u32) -> (Self, IResult<CompleteStr, u32>) {
        self.numbers.insert(n);
        (self, Ok((inp, n)))
    }

    method!(read_num<Registry, CompleteStr, u32>, mut self,
        do_parse!(
            num: map_res!(digit, nom_u32) >>
            num: call_m!(self.reg_num, num) >>
            (num))
    );
    method!(read_list<Registry, CompleteStr, Vec<u32>>, mut self,
        delimited!(
            tag!("["),
            separated_list!(tag!(","), call_m!(self.read_num)),
            tag!("]"))
    );
}
```

This results in:

```
error[E0382]: use of moved value: `self`
  --> src/lib.rs:27:5
   |
27 |        method!(list<Registry, CompleteStr, Vec<u32>>, mut self,
   |   _____^
   |  |_____|
   | ||
28 | ||         delimited!(
29 | ||             tag!("["),
30 | ||             separated_list!(tag!(","), call_m!(self.num)),
31 | ||             tag!("]"))
32 | ||     );
   | ||      ^
   | ||______|
   | |_______value used here after move
   |         value moved (into closure) here
   |
   = note: move occurs because `self` has type `Registry`, which does not implement the `Copy` trait
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

A workaround is to use `do_parse!` instead of `delimited!`.

To see exactly what's happening, here's a trace of the macro expansion:

```
note: trace_macro
  --> src/lib.rs:30:5
   |
30 | /     method!(list<Registry, CompleteStr, Vec<u32>>, mut self,
31 | |         delimited!(
32 | |             tag!("["),
33 | |             separated_list!(tag!(","), call_m!(self.num)),
34 | |             tag!("]"))
35 | |     );
   | |______^
   |
   = note: expanding `method! { list < Registry , CompleteStr , Vec < u32 >> , mut self , delimited ! (
           tag ! ( "[" ) , separated_list ! ( tag ! ( "," ) , call_m ! ( self . num ) ) ,
           tag ! ( "]" ) ) }`
   = note: to `# [ allow ( unused_variables ) ] fn list (
           mut self : Registry , i : CompleteStr ) -> (
           Registry , $crate :: IResult < CompleteStr , Vec<u32> , u32 > ) {
           let result = delimited ! (
           i , tag ! ( "[" ) , separated_list ! ( tag ! ( "," ) , call_m ! ( self . num )
           ) , tag ! ( "]" ) ) ; ( self , result ) }`
   = note: expanding `delimited! { i , tag ! ( "[" ) , separated_list ! ( tag ! ( "," ) , call_m ! ( self . num )
           ) , tag ! ( "]" ) }`
   = note: to `{
           use :: std :: result :: Result :: * ; match tuple_parser ! (
           i , (  ) , tag ! ( "[" ) , separated_list ! (
           tag ! ( "," ) , call_m ! ( self . num ) ) , tag ! ( "]" ) ) {
           Err ( e ) => Err ( e ) , Ok ( ( i1 , ( _ , o , _ ) ) ) => { Ok ( ( i1 , o ) )
           } } }`
   = note: expanding `tuple_parser! { i , (  ) , tag ! ( "[" ) , separated_list ! (
           tag ! ( "," ) , call_m ! ( self . num ) ) , tag ! ( "]" ) }`
   = note: to `{
           let i_ = i . clone (  ) ; ( tag ! ( i_ , "[" ) ) . and_then (
           | ( i , o ) | {
           let i_ = i . clone (  ) ; tuple_parser ! (
           i_ , ( o ) , separated_list ! ( tag ! ( "," ) , call_m ! ( self . num ) ) ,
           tag ! ( "]" ) ) } ) }`
   = note: expanding `tag! { i_ , "[" }`
   = note: to `{
           use :: std :: result :: Result :: * ; use $crate :: {
           Err , Needed , IResult , ErrorKind } ; use $crate :: {
           Compare , CompareResult , InputLength , need_more , InputTake } ; let res :
           IResult < _ , _ > = match ( i_ ) . compare ( "[" ) {
           CompareResult :: Ok => {
           let blen = "[" . input_len (  ) ; Ok ( i_ . take_split ( blen ) ) } ,
           CompareResult :: Incomplete => {
           need_more ( i_ , Needed :: Size ( "[" . input_len (  ) ) ) } , CompareResult
           :: Error => {
           let e : ErrorKind < u32 > = ErrorKind :: Tag ; Err (
           Err :: Error ( $crate :: Context :: Code ( i_ , e ) ) ) } } ; res }`
   = note: expanding `tuple_parser! { i_ , ( o ) , separated_list ! ( tag ! ( "," ) , call_m ! ( self . num ) ) ,
           tag ! ( "]" ) }`
   = note: to `{
           let i_ = i_ . clone (  ) ; (
           separated_list ! ( i_ , tag ! ( "," ) , call_m ! ( self . num ) ) ) . and_then
           (
           | ( i , o ) | {
           let i_ = i . clone (  ) ; tuple_parser ! ( i_ , ( o , o ) , tag ! ( "]" ) ) }
           ) }`
   = note: expanding `separated_list! { i_ , tag ! ( "," ) , call_m ! ( self . num ) }`
   = note: to `{
           use :: std :: result :: Result :: * ; use $crate :: Err ; use $crate ::
           InputLength ; let mut res = :: std :: vec :: Vec :: new (  ) ; let mut input =
           i_ . clone (  ) ; let input_ = input . clone (  ) ; match call_m ! (
           input_ , self . num ) {
           Err ( Err :: Error ( _ ) ) => Ok ( ( input , res ) ) , Err ( e ) => Err ( e )
           , Ok ( ( i , o ) ) => {
           if i . input_len (  ) == input . input_len (  ) {
           Err (
           Err :: Error (
           error_position ! ( input , $crate :: ErrorKind :: SeparatedList ) ) ) } else {
           res . push ( o ) ; input = i ; let ret ; loop {
           let input_ = input . clone (  ) ; match tag ! ( input_ , "," ) {
           Err ( Err :: Error ( _ ) ) => { ret = Ok ( ( input , res ) ) ; break ; } Err (
           e ) => { ret = Err ( e ) ; break ; } , Ok ( ( i2 , _ ) ) => {
           let i2_len = i2 . input_len (  ) ; if i2_len == input . input_len (  ) {
           ret = Ok ( ( input , res ) ) ; break ; } match call_m ! ( i2 , self . num ) {
           Err ( Err :: Error ( _ ) ) => { ret = Ok ( ( input , res ) ) ; break ; } , Err
           ( e ) => { ret = Err ( e ) ; break ; } , Ok ( ( i3 , o3 ) ) => {
           if i3 . input_len (  ) == i2_len { ret = Ok ( ( input , res ) ) ; break ; }
           res . push ( o3 ) ; input = i3 ; } } } } } ret } } , } }`
   = note: expanding `tuple_parser! { i_ , ( o , o ) , tag ! ( "]" ) }`
   = note: to `{
           let i_ = i_ . clone (  ) ; ( tag ! ( i_ , "]" ) ) . map (
           | ( i , o ) | ( i , ( o , o , o ) ) ) }`
   = note: expanding `tag! { i_ , "]" }`
   = note: to `{
           use :: std :: result :: Result :: * ; use $crate :: {
           Err , Needed , IResult , ErrorKind } ; use $crate :: {
           Compare , CompareResult , InputLength , need_more , InputTake } ; let res :
           IResult < _ , _ > = match ( i_ ) . compare ( "]" ) {
           CompareResult :: Ok => {
           let blen = "]" . input_len (  ) ; Ok ( i_ . take_split ( blen ) ) } ,
           CompareResult :: Incomplete => {
           need_more ( i_ , Needed :: Size ( "]" . input_len (  ) ) ) } , CompareResult
           :: Error => {
           let e : ErrorKind < u32 > = ErrorKind :: Tag ; Err (
           Err :: Error ( $crate :: Context :: Code ( i_ , e ) ) ) } } ; res }`
   = note: expanding `call_m! { i2 , self . num }`
   = note: to `{ let ( tmp , res ) = self . num ( i2 ) ; self = tmp ; res }`
   = note: expanding `tag! { input_ , "," }`
   = note: to `{
           use :: std :: result :: Result :: * ; use $crate :: {
           Err , Needed , IResult , ErrorKind } ; use $crate :: {
           Compare , CompareResult , InputLength , need_more , InputTake } ; let res :
           IResult < _ , _ > = match ( input_ ) . compare ( "," ) {
           CompareResult :: Ok => {
           let blen = "," . input_len (  ) ; Ok ( input_ . take_split ( blen ) ) } ,
           CompareResult :: Incomplete => {
           need_more ( input_ , Needed :: Size ( "," . input_len (  ) ) ) } ,
           CompareResult :: Error => {
           let e : ErrorKind < u32 > = ErrorKind :: Tag ; Err (
           Err :: Error ( $crate :: Context :: Code ( input_ , e ) ) ) } } ; res }`
   = note: expanding `error_position! { input , $crate :: ErrorKind :: SeparatedList }`
   = note: to `{ $crate :: Context :: Code ( input , ::ErrorKind::SeparatedList ) }`
   = note: expanding `call_m! { input_ , self . num }`
   = note: to `{ let ( tmp , res ) = self . num ( input_ ) ; self = tmp ; res }`
```

You can see that `self` is being moved into `and_then` during expansion of tuple_parser — I think this is the problem.

**Comment by z2oh** [comment] 2018-11-10 01:40
@Geal any update on this? We are experiencing this issue for our parser. We have had to refactor a lot of the code to use `do_parse!` instead of these convenience methods.

**Comment by Geal** [comment] 2018-11-11 13:39
@lucasem @z2oh currently I don't have the time to investigate this issue. If you're willing to debug it and propose a fix, I'd guess the issue is more in the method combinators that rely on consuming `self`, returning it with the result and reassigning it.
Maybe they could use a `&mut self` instead.

**Comment by Geal** [comment] 2019-05-05 10:45
closing this for now, feel free to reopen if there's new info on this

**Closed by Geal** 2019-05-05 10:45 UTC
