### ISSUE TITLE
Many0 without Clone possible?

### ISSUE THREAD

**Issue by ede1998** [Geal/nom#1329] opened 2021-06-22 20:32 UTC
I noticed that `many0` (and possibly others) clones the input to check if it is still the same after the embedded parser was applied. It does so to prevent the embedded parser from accepting empty inputs, which would cause infinite loops.

I wondered if it is really necessary to clone the input for this.
Wouldn't it suffice to just compare the input length? If it's still the same after the embedded parser was applied, an empty input was accepted.

Am I missing something here? Is it possible to mutate the input in a parser?
If not, I'd be open to try and implement a simple length check instead of clone.

**Comment by Lucretiel** [comment] 2021-06-28 18:37
I think the problem is that parsers take input by `move`. That is, if you do:

```
let input1 = ...;
let (input2, result) = parser.parse(input1)?;
```

It's not possible to compare `input1` and `input2`, because `input1` was moved into the parser. In practice the `clone` isn't a problem, because inputs to nom are very cheap to clone (for instance, `Clone` for `&str` and `&[u8]` is a single pointer copy)

**Comment by ede1998** [comment] 2021-06-29 08:52
Thanks for the answer.

>I think the problem is that parsers take input by `move`.

I implemented an `all0` parser that works very similar to the `many0` parser of nom. The difference is that it fails if it did not consume the entire input. I could avoid the borrow checker there quite easily.

```rust
    pub fn all0<I, O, E, F>(mut f: F) -> impl FnMut(I) -> IResult<I, Vec<O>, E>
    where
        I: InputLength,
        F: Parser<I, O, E>,
        E: NomParseError<I>,
    {
        move |mut i: I| {
            let mut acc = Vec::with_capacity(4);
            let mut old_len = i.input_len();
            while old_len > 0 {
                match f.parse(i) {
                    Ok((inner, o)) => {
                        let new_len = inner.input_len();
                        if new_len == old_len {
                            return Err(Err::Error(E::from_error_kind(inner, NomErrorKind::Many0)));
                        }
                        acc.push(o);
                        i = inner;
                        old_len = new_len;
                    }
                    Err(e) => return Err(e),
                }
            }
            Ok((i, acc))
        }
    }
```
https://github.com/ede1998/knx_tun/blob/691a26dab31b51b8284aa0b95e75e00624053dbf/src/snack.rs#L209-L234

> In practice the clone isn't a problem

I get now that the clone is not a problem. I thought that Clone was expensive for reference types, which it is apparently not. However, if I'm reading the PartialEq implementation for references correctly, this is a potentially slow O(n) operation (for slices), which `many0` does every loop iteration. So there is still that, which should maybe be avoided?

```rust
impl<A: ?Sized, B: ?Sized> PartialEq<&B> for &A
    where
        A: PartialEq<B>,
    {
        #[inline]
        fn eq(&self, other: &&B) -> bool {
            PartialEq::eq(*self, *other)
        }
        #[inline]
        fn ne(&self, other: &&B) -> bool {
            PartialEq::ne(*self, *other)
        }
    }
```
https://doc.rust-lang.org/src/core/cmp.rs.html#1333-1345

**Comment by Geal** [comment] 2021-08-09 16:31
a `&[u8]` slice is a special type made of a pointer and a length. It implements `Copy`, so cloning is cheap, and `PartialEq` will do a `memcmp` comparison ( https://doc.rust-lang.org/src/core/slice/cmp.rs.html#79 ) which can be a bit faster than going byte by byte, but you're right, we could just check on the length.

There's a potential for more bugs here if a parser breaks the invariant of the remaining data being a suffix of the input, but the infinite loop check is not here for that anyway

**Comment by Geal** [comment] 2021-08-09 17:00
this is fixed by 173ce1c. Note that there's no noticeable performance improvement for `&[u8]` and `&str` since their `PartialEq` implementation begins with a length check. That would only improve performance in case the child parser did not consume anything. At least that will generate less code

**Comment by ede1998** [comment] 2021-08-09 17:56
Thanks for looking into this!
> no noticeable performance improvement for `&[u8]` and `&str` since their `PartialEq` implementation begins with a length check

I was hoping for more but I guess that makes sense.

I had a look at your commit and if I'm not mistaken, you can remove most `Clone` bounds of the combinators to make the code a bit easier to understand.

**Comment by Geal** [comment] 2021-08-09 18:42
The clone is still necessary to return the accumulated data and the remaining input if the parser failed

**Comment by Geal** [comment] 2021-08-21 11:14
released in nom 7: https://crates.io/crates/nom/7.0.0

**Closed by Geal** 2021-08-21 11:14 UTC
Labels: needs testing
