### ISSUE TITLE
take_till1 compile problem

### ISSUE THREAD

**Issue by steven807** [Geal/nom#775] opened 2018-05-19 18:48 UTC
## Prerequisites

- Rust version : rustc 1.28.0-nightly (952f344cd 2018-05-18)
- nom version : 4.0.0
- nom compilation features used: none

## Test case
```
#[macro_use]
extern crate nom;

named!(p, take_till1!(|_| true));

fn main() {
    let _ = p(b"abc");
}
```
This fails to compile with:
```
error[E0433]: failed to resolve. Use of undeclared type or module `ErrorKind`
 --> src/main.rs:4:1
  |
4 | named!(p, take_till1!(|_| true));
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Use of undeclared type or module `ErrorKind`
  |
```

**Comment by Geal** [comment] 2018-08-18 15:45
hello, this compiles correctly with nom 4, were you using the version from crates.io or one directly from github master?

**Comment by steven807** [comment] 2018-08-18 16:40
I'm using crates.io.  For completeness, here's the entire Cargo.toml.

    [package]
    name = "nombug"
    version = "0.1.0"
    
    [dependencies.nom]
    version = "4.*"

The source tree consists solely of that `Cargo.toml` file, and the original `src/main.rs`.  I just checked again, with `stable-x86_64-apple-darwin`: `rustc 1.28.0 (9634041f0 2018-07-30)`, and the same problem arises.

**Comment by Geal** [comment] 2018-10-06 14:10
hello,

does this bug still appear? I added your example to nom's unit tests in 0009b60, but still cannot reproduce the bug

**Comment by Geal** [comment] 2018-10-06 15:28
closing this for now, feel free to reopen if the bug is still there

**Closed by Geal** 2018-10-06 15:28 UTC
