### ISSUE TITLE
Option::unwrap() on a None value, in src/error.rs:190

### ISSUE THREAD

**Issue by ZirconiumX** [Geal/nom#1027] opened 2019-09-06 12:10 UTC
## Prerequisites

Here are a few things you should provide to help me understand the issue:

- Rust version : `rustc 1.37.0 (eae3437df 2019-08-13)`
- nom version : `5.0.1`
- nom compilation features used: [the default, I haven't modified any]

## Test case

```
use nom::{
    bytes::complete::take_while,
    character::complete::newline,
    error::{convert_error, ParseError, VerboseError},
    sequence::terminated,
    Err, IResult,
};

pub fn bug<'a, E: ParseError<&'a str>>(s: &'a str) -> IResult<&'a str, &'a str, E> {
    terminated(
        take_while(|c| c == 'a'),
        newline, // opt(newline) fixes it
    )(s)
}

fn main() {
    match bug::<VerboseError<&str>>("aaaa") {
        Err(Err::Error(e)) => println!("Error: {}", convert_error("aaaa", e)), // This should not panic!
        _ => unreachable!(),
    }
}
```

Here, `VerboseError` tries to look for the trailing newline in the source string, which does not exist, causing it to crash. That's my understanding of the bug, anyway.

**Comment by sthiele** [comment] 2019-12-13 17:40
I ran into the same problem.
@Alxandr the patch looks good.

**Comment by sthiele** [comment] 2019-12-13 21:20
duplicate of #986 
alternative PR #970

**Closed** 2020-01-07 16:43 UTC
