### ISSUE TITLE
`recognize!` fails to copy parsed data from `take_while!`

### ISSUE THREAD

**Issue by kerinin** [Geal/nom#235] opened 2016-03-07 00:14 UTC
Not sure if this affects other macros, but this fails for me:

```rust
named!(x, take_while!(is_alphanumeric));
named!(y, recognize!(x));
assert_eq!(y(&b"ab"[..]), Done(&[][..], &b"ab"[..]));
// (left: `Done([], [])`, right: `Done([], [50, 50])`)'
```

**Comment by Geal** [comment] 2016-03-08 18:05
This was caused by an error in `take_while!`:
When the whole input was consumed, it returned `Done(&input[..0], input)` instead of `Done(&input[input.len()..], input)`. While in both cases, the remaining slice is empty, its position compared to the input is not the same, and `recognize!` uses that position.

Fixed in 8623633

**Closed by Geal** 2016-03-08 18:05 UTC
