### ISSUE TITLE
Change docs to use non-macro names for Nom 5+.

### ISSUE THREAD

**Issue by CinchBlue** [Geal/nom#1290] opened 2021-02-26 06:46 UTC
Nom's implementation now relies on functions internally vs. using macros before.

Many of the docs still use the old macro names, which is the non-idiomatic way to use Nom as of the time of writing. This can create an impediment for users (like me -- I just spent a large amount of time trying to self-start after the version bump).

I am filing this issue to so that Nom contributors can discuss this.

**Comment by Geal** [comment] 2021-03-13 11:17
could you point at which docs require an update?

**Comment by neokril** [comment] 2021-03-18 21:55
This one: [choosing_a_combinator.md](https://github.com/Geal/nom/blob/master/doc/choosing_a_combinator.md). Column «usage» and a text below the tables.

**Comment by cgarciae** [comment] 2021-05-02 15:59
Possibly this needs to be updated?

https://github.com/Geal/nom/blob/master/doc/choosing_a_combinator.md

**Comment by ottosson** [comment] 2021-05-17 07:24
Duplicate of #1140 ?
I started to restructure the list but never got any feedback, so I never finished the page. But if you like the structure I could continue the work: https://github.com/ottosson/nom/blob/master/doc/choosing_a_combinator.md (only the first table is updated at the moment).

**Closed** 2021-06-19 10:14 UTC
